version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      consul:
        condition: service_healthy
      redis:
        condition: service_healthy
      vault:
        condition: service_started
      vault-init:
        condition: service_completed_successfully
    environment:
      # DEVELOPMENT PURPOSE ONLY - DO NOT DO THIS IN PRODUCTION
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root"
      VAULT_JWT_PATH: "/v1/secret/data/jwt"
    volumes:
      - .:/app
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: authentication_db
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  consul:
    image: hashicorp/consul:latest
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5

  consul-config:
    image: hashicorp/consul:latest
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    entrypoint: /bin/sh
    command: -c "sleep 7 && \
      consul kv put config/mysql/host mysql && \
      consul kv put config/mysql/port 3306 && \
      consul kv put config/mysql/user user && \
      consul kv put config/mysql/password P@ssw0rd! && \
      consul kv put config/mysql/database authentication_db && \
      consul kv put config/redis/host redis && \
      consul kv put config/redis/port 6379 && \
      consul kv put config/redis/password '' && \
      consul kv put config/mysql/connection/maxLifeTime 180 && \
      consul kv put config/mysql/connection/idleConnections 10 && \
      consul kv put config/mysql/connection/maxOpenConnections 10"

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: "server -dev -dev-root-token-id=root"
    volumes:
      - vault-data:/vault/file
    healthcheck:
      test: [ "CMD", "curl", "-f", "-s", "-o", "/dev/null", "-w", "%{http_code}", "http://localhost:8200/v1/sys/health", "-m", "15" ]
      interval: 15s
      timeout: 15s
      retries: 30

  vault-init:
    image: hashicorp/vault:latest
    depends_on:
      - vault
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo "Initializing Vault with jwt tokens..."
        sleep 2
        vault login root
        vault kv put secret/jwt jwtSecret="jwt_secret_value" jwtRefreshSecret="jwt_refresh_token_value"
        echo "Vault initialized with jwt secrets."
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root"
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 5s
      timeout: 2s
      retries: 1

volumes:
  mysql-data:
  vault-data: