version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - consul
      - redis
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: authentication_db
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  consul:
    image: hashicorp/consul:latest
    restart: always
    ports:
      - "8500:8500"     
      - "8600:8600/udp"  
    command: "agent -server -bootstrap -ui -client=0.0.0.0"

  consul-config:
    image: hashicorp/consul:latest
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=http://consul:8500
    entrypoint: /bin/sh
    command: -c "sleep 7 && \
      consul kv put config/mysql/host mysql && \
      consul kv put config/mysql/port 3306 && \
      consul kv put config/mysql/user user && \
      consul kv put config/mysql/password P@ssw0rd! && \
      consul kv put config/mysql/database authentication_db && \
      consul kv put config/redis/host redis && \
      consul kv put config/redis/port 6379 && \
      consul kv put config/redis/password ''"
      consul kv put config/mysql/connection/maxLifeTime 180
      consul kv put config/mysql/connection/idleConnections 10
      consul kv put config/mysql/connection/maxOpenConnections 10



  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      # Vault dev mode: DO NOT use these settings in production!
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: "server -dev -dev-root-token-id=root"
    # Optional: persist logs to view the token details if needed.
    volumes:
      - vault-data:/vault/file

  vault-init:
      image: hashicorp/vault:latest
      depends_on:
        - vault
      entrypoint: /bin/sh
      command:
        - -c
        - |
          echo "start of putting of jwt tokens in vault, starts in 5 seconds"
          sleep 5
          vault login root
          vault kv put secret/jwt jwtSecret="jwt_secret_value" jwtRefreshSecret="jwt_refresh_token_value"
          echo "Vault initialized with jwt secrets."
      environment:
        VAULT_ADDR: "http://vault:8200"
        VAULT_TOKEN: "root"

volumes:
  mysql-data:
  vault-data:
