// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/SilentPlaces/basicauth.git/internal/config"
	"github.com/SilentPlaces/basicauth.git/internal/services/consul"
)

// Injectors from wire.go:

// InitializeConsulService initializes a ConsulService using dependencies from config and services packages.
func InitializeConsulService() *consul.ConsulService {
	appConfig := config.LoadConfig()
	consulService := consul.NewConsulService(appConfig)
	return consulService
}
